# Generated by Django 5.0.6 on 2024-05-21 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviation_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='arrival_airport',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='arrival_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_airport',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='flight_number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
