# Generated by Django 5.0.6 on 2024-05-21 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviation_data', '0002_alter_flight_arrival_airport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='airport',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='airport',
            name='iata_code',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='airport',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
